pipeline {
    agent {
        docker {
                image 'registry.opensuse.org/isv/suseinfra/containers/containerfile/suseinfra/salt-ci-lint'
                label 'docker' 
        }
    }
    stages {
        stage('build') {
            steps {
                sh 'python3 --version'
                sh 'echo $HOSTNAME && echo $(pwd)'
            }
        }
        stage('lint') {
            steps {
                sh 'set -x; find . -type f \\( -name \'*.yaml\' -o -name \'*.yml\' \\) -exec yamllint -f colored -s {} +'
                sh 'set -x; find . -name \'*.sls\' -exec salt-lint --severity {} +'
            }
        }
    }
}
